### PR TITLE
Create Readme

### PR DESCRIPTION
**Pull request by MrJefff**

### CODE REVIEW

**Comment by lukespragg** [comment]
Please hold off on these for now @MrJefff, would save me some time having to remove parts that aren't supposed to be there or do not match the headers needed for injection.

**Comment by MrJefff** [comment]
Ok. I'll stop doing it all (Have some ready to be merged). Just trying to help out and fill in the blanks.
There are only a few with dependencies that "link"  back to OxideMod.
I'm also not sure how uMod reads the readme(s) so was expecting my pulls to be edited anyway.

**Comment by lukespragg** [comment]
Things such as the images and other random links wouldn’t get carried over directly, that it something we’d be working on adding later via a gallery.

The varying header names would have to be changed to be more standard in order for help tips to be injected. Examples of this would be Confirguration, Permissions, Localization, etc.  A lot of the descriptions are missing some information about their permissions, localization, logging, and commands too; so that is also something that needs to be reviewed.

For the initial migration, it is one less step to just commit it with the changes needed rather than pulling down to edit a commit or committing again after a pull request to add the missing parts.

I appreciate the desire to help though! If you would like to work on something, feel free to message me back in the PM for a link to Discord.

**Comment by MrJefff** [comment]
Ah I see, I'll leave them for now then.

Sure, i don't mind helping out as long as its not too convoluted.

**Pull request closed without merging**
